# Generated by Django 3.0.7 on 2020-06-17 09:48

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=teachers.models.get_image_path)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('room_number', models.CharField(max_length=10)),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('computer_science', 'Computer science'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('history', 'History'), ('geography', 'Geography'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English'), ('arabic', 'Arabic')], max_length=20)),
            ],
        ),
    ]
